SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDACM.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDAPAE.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDBALFOUR.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDBENCH.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDCONTAB.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDDARF.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDFEDEX.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDFEDEX_teste.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDFUPAM.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDGRC.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDGSR7.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDHOLLINGSORIG.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDINFORMATEC.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDINFORMATECteste.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDINTEG.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDINTEG_AGIW.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDINTEG_DDBROKER.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDJAVA.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDJEDI.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDLETAFLEX.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDLETANDE.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDLIVROISS.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDLIVROISSpryor.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDMERIDIAN.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDMETROCABLE.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDMGSUL.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDPROSANGUE.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDSANPHAR.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDSPARTAN.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDSPARTANET.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDSUPPLY.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDTEF.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDTREINAMENTO.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDUNIP.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM BDVAZIO.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM DBCBAN.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM Fluxo.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM master.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM model.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM msdb.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM Northwind.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM pubs.dbo.sysfiles o 
SELECT CAST(o.name AS CHAR(30)) AS name, o.filename FROM tempdb.dbo.sysfiles o 