UPDATE TBLFIS007 
SET VALBASECALCPISCOFINSIMPORT = (CASE
                                   WHEN I.VALBASECALCPISCOFINSIMPORT > 0 THEN I.VALBASECALCPISCOFINSIMPORT
                                   ELSE (CASE G.TIPBASECALCPIS
                                          WHEN '1' THEN I.VALMERCSEMICM
                                          ELSE I.VALMERCSEMICM + I.VALICMSDESTACADO + I.VALFRETE + I.VALSEGURO + I.VALDESPESAS
                                         END )
                                  END),
    VALCOFINSRECUPERADO = I.VALCOFINSRECUPERADO,
    VALPISRECUPERADO    = I.VALPISRECUPERADO,
    PERCCOFINS          = I.PERCCOFINS,
    PERCPIS             = I.PERCPIS 
FROM TBLFIS005 L, TBCOMP018 N, TBCOMP019 I, TBGENE035 G
WHERE YEAR(L.DATCOMPET) = 2011
  AND N.CODEMP    = L.CODEMP
  AND N.NUMNF     = L.NUMNF
  AND N.SERNF     = L.SERIENFORIGEM
  AND N.CODFORN   = L.CODFORN
  AND I.CODEMP    = N.CODEMP
  AND I.NUMNF     = N.NUMNF
  AND I.SERNF     = N.SERNF
  AND I.CODFORN   = N.CODFORN
  AND (I.VALCOFINSRECUPERADO > 0 OR I.VALPISRECUPERADO > 0)
  AND TBLFIS007.CODEMP    = L.CODEMP
  AND TBLFIS007.NUMNF     = L.NUMNF
  AND TBLFIS007.SERNF     = L.SERNF
  AND TBLFIS007.CODFORN   = L.CODFORN
  AND TBLFIS007.NUMITEM   = I.NUMITEMNF 
  AND G.CODEMP    = L.CODEMP
GO  

UPDATE TBLFIS007 
SET VALBASECALCPISCOFINSIMPORT = (CASE
                                   WHEN I.VALBASECALCPISCOFINSIMPORT > 0 THEN I.VALBASECALCPISCOFINSIMPORT
                                   ELSE (CASE G.TIPBASECALCPIS
                                          WHEN '1' THEN I.VALMERCSEMICM
                                          ELSE I.VALMERCSEMICM + I.VALICMSDESTACADO + I.VALFRETE + I.VALSEGURO + I.VALDESPESAS
                                         END )
                                  END),
    VALCOFINSRECUPERADO = I.VALCOFINSRECUPERADO,
    VALPISRECUPERADO    = I.VALPISRECUPERADO,
    PERCCOFINS          = I.PERCCOFINS,
    PERCPIS             = I.PERCPIS        
FROM TBLFIS005 L, TBCOMP022 N, TBCOMP023 I, TBGENE035 G
WHERE YEAR(L.DATCOMPET) = 2011
  AND N.CODEMP    = L.CODEMP
  AND N.NUMNF     = L.NUMNF
  AND N.SERNF     = L.SERIENFORIGEM
  AND N.CODFORN   = L.CODFORN
  AND I.CODEMP    = N.CODEMP
  AND I.NUMNF     = N.NUMNF
  AND I.SERNF     = N.SERNF
  AND I.CODFORN   = N.CODFORN
  AND (I.VALCOFINSRECUPERADO > 0 OR I.VALPISRECUPERADO > 0)
  AND TBLFIS007.CODEMP    = L.CODEMP
  AND TBLFIS007.NUMNF     = L.NUMNF
  AND TBLFIS007.SERNF     = L.SERNF
  AND TBLFIS007.CODFORN   = L.CODFORN
  AND TBLFIS007.NUMITEM   = I.NUMITEMNF 
  AND G.CODEMP    = L.CODEMP
GO  
  

UPDATE TBLFIS007 
SET VALBASECALCPISCOFINSIMPORT = (CASE
                                   WHEN I.VALBASECALCPISCOFINSIMPORT > 0 THEN I.VALBASECALCPISCOFINSIMPORT
                                   ELSE I.VALTOTITEM + I.VALDESCICMS  - I.VALIPI - I.VALICMSSUBST
                                  END),
    VALCOFINSRECUPERADO = ROUND(I.VALCOFINS * (M.PERCRECUPCOFINS / 100),2),
    VALPISRECUPERADO    = ROUND(I.VALPIS    * (M.PERCRECUPPIS    / 100),2),
    PERCCOFINS          = I.VALPERCCOFINS,
    PERCPIS             = I.VALPERCPIS        
FROM TBLFIS005 L, TBFATU024 N, TBFATU025 I, TBGENE035 G, TBFATU018 M
WHERE YEAR(L.DATCOMPET) = 2011
  AND N.CODEMP    = L.CODEMP
  AND N.NUMNF     = L.NUMNF
  AND N.SERNF     = L.SERIENFORIGEM
  AND N.CODCLI    = L.CODEMITORIG
  AND I.CODEMP    = N.CODEMP
  AND I.NUMNF     = N.NUMNF
  AND I.SERNF     = N.SERNF
  AND TBLFIS007.CODEMP    = L.CODEMP
  AND TBLFIS007.NUMNF     = L.NUMNF
  AND TBLFIS007.SERNF     = L.SERNF
  AND TBLFIS007.CODFORN   = L.CODFORN
  AND TBLFIS007.NUMITEM   = I.NUMITEMNF 
  AND G.CODEMP    = L.CODEMP
  AND M.CODMOVFISC = I.CODMOVFISC
  AND (M.PERCRECUPCOFINS > 0 OR M.PERCRECUPPIS > 0)
GO  
