 SELECT X.*
      , (X.BASEICMS_ITENS - X.BASEICMS_RECALC) AS DIFERENCA
      , CASE X.TIPRATEIOFRETENF
         WHEN '1' THEN SUM( (I.VALMERCSEMIMP  * X.FATORRATEIOFRETE) + (I.VALMERCSEMIMP  * X.FATORRATEIODA) )
         WHEN '2' THEN SUM( (I.PESOLIQTOTITEM * X.FATORRATEIOFRETE) + (I.VALMERCSEMIMP  * X.FATORRATEIODA) )
        END AS RATEIOFRETE
 FROM 
 (
 SELECT N.CODEMP,
        N.NUMNF,
        N.SERNF,
        N.DATEMISSAO,
        N.VALTOTNF,
        N.VALTOTMERC,
        N.VALTOTICM,
        ISNULL(N.VALFRETE,0) VALFRETE,
        ISNULL(N.VALSEGURO,0) VALSEGURO,
        ISNULL(N.VALOUTROS,0) VALOUTROS,
        ( ISNULL(N.VALFRETE,0)+
          ISNULL(N.VALSEGURO,0)+
          ISNULL(N.VALOUTROS,0) ) AS TOT_DA_CAPA,
        SUM(ISNULL(I.VALRATEIODA,0))    VALRATEIODA_ITENS,
        SUM(ISNULL(I.VALRATEIOFRETE,0)) VALRATEIOFRETE_ITENS,
        SUM(ISNULL(I.VALRATEIOSEG,0))   VALRATEIOSEG_ITENS,
        G.TIPRATEIOFRETENF,
        C.BASECALCICMDESTINO,
        CASE G.TIPRATEIOFRETENF
         WHEN '1' THEN ISNULL(N.VALFRETE,0) / N.VALTOTMERC
         WHEN '2' THEN ISNULL(N.VALFRETE,0) / (CASE SUM(I.PESOLIQTOTITEM) WHEN 0 THEN 1 ELSE SUM(I.PESOLIQTOTITEM) END) 
        END AS FATORRATEIOFRETE,
        ( (N.VALOUTROS+N.VALSEGURO) / N.VALTOTMERC) AS FATORRATEIODA,
        ( N.VALOUTROS / N.VALTOTMERC) AS FATORRATEIOOUTROS,
        ( N.VALSEGURO / N.VALTOTMERC) AS FATORRATEIOSEGURO,
        ROUND(N.BASECALCICMS,2) BASEICMS_CAPA,
        SUM(I.VALBASECALCICM) AS BASEICMS_ITENS,
        CASE C.BASECALCICMDESTINO
         WHEN '4' THEN SUM ( ROUND((I.VALMERCSEMIMP + I.VALIMPIMPORT + I.VALIPI + I.VALRATEIODA +
                                    I.VALPIS + I.VALCOFINS) / ((100 - I.VALPERCICM)/100)- I.VALBASEREDUZIDA,2) )  
         WHEN '3' THEN SUM ( ROUND((I.VALMERCSEMIMP + I.VALIMPIMPORT + I.VALIPI + I.VALRATEIODA) 
                                    / ((100 - I.VALPERCICM)/100)- I.VALBASEREDUZIDA,2))  
         WHEN '2' THEN SUM ( ROUND((I.VALMERCSEMIMP + I.VALRATEIODA)- I.VALBASEREDUZIDA,2))  
         WHEN '1' THEN SUM ( ROUND((I.VALMERCSEMIMP + I.VALIPI + I.VALRATEIODA)- I.VALBASEREDUZIDA,2))  
         WHEN '0' THEN SUM ( ROUND((I.VALMERCSEMIMP + I.VALIPI )- I.VALBASEREDUZIDA,2))  
         ELSE 0 END AS BASEICMS_RECALC
  FROM TBFATU024 N,
       TBFATU025 I,
       TBFATU018 C,
       TBGENE035 G
 WHERE N.STANF <> 'C'
   AND N.TIPONF NOT IN ('7', '8')
   AND ISNULL(N.VALDESPESAS,0)+
       ISNULL(N.VALFRETE,0)+
       ISNULL(N.VALSEGURO,0)+
       ISNULL(N.VALOUTROS,0) > 0 
   AND I.CODEMP = N.CODEMP
   AND I.NUMNF  = N.NUMNF
   AND I.SERNF  = N.SERNF
   AND C.CODMOVFISC = I.CODMOVFISC
   AND C.BASECALCICMDESTINO IN ('1','2','3','4')
   AND C.FATORBASECALCICM <> 0
   AND G.CODEMP = N.CODEMP
GROUP BY N.CODEMP, N.NUMNF,
        N.SERNF,
        N.DATEMISSAO,
        N.VALTOTNF,
        N.BASECALCICMS,
        N.VALTOTICM,
        N.VALTOTMERC,
        N.VALFRETE,
        N.VALSEGURO,
        N.VALOUTROS,
        G.TIPRATEIOFRETENF,
        C.BASECALCICMDESTINO
) AS X
  INNER JOIN TBFATU025 I
  ON I.CODEMP = X.CODEMP
 AND I.NUMNF  = X.NUMNF
 AND I.SERNF  = X.SERNF
WHERE X.BASEICMS_ITENS <> X.BASEICMS_RECALC
GROUP BY X.CODEMP, X.NUMNF, X.SERNF, X.DATEMISSAO, X.VALTOTNF, X.VALTOTMERC,
         X.VALTOTICM, X.VALFRETE, X.VALSEGURO, X.VALOUTROS, X.TOT_DA_CAPA, 
         X.VALRATEIODA_ITENS, X.VALRATEIOFRETE_ITENS, X.VALRATEIOSEG_ITENS,
         X.TIPRATEIOFRETENF, X.BASECALCICMDESTINO, X.FATORRATEIOFRETE, X.FATORRATEIODA, X.FATORRATEIOOUTROS, X.FATORRATEIOSEGURO,
         X.BASEICMS_CAPA, X.BASEICMS_ITENS, X.BASEICMS_RECALC
ORDER BY 4, 3, 2
       
