SELECT T.CODCLI,
       C.NUMCGCCPFCLI,
       C.RAZSOCCLI,
       min(DATPRORROGA) AS PRIMVENCTO,
       cast(GETDATE() - min(DATPRORROGA) as int) AS MAIORATRASO,
       SUM(VALSDARECEBER) AS VALABERTO,
       W.PERCEMDIA,
       W.PERCEM30,
       W.PERCMAIS30
FROM TBCTRC002 T
LEFT JOIN TBFATU006 C ON C.CODCLI = T.CODCLI
LEFT JOIN 
(SELECT CODCLI, (EMDIA +EM30 + MAISDE30) AS TOTALATRASO,
        ROUND(CAST(EMDIA    AS DECIMAL(6,3)) *100  / (EMDIA +EM30 + MAISDE30), 3)  AS PERCEMDIA,
        ROUND(CAST(EM30     AS DECIMAL(6,3)) *100  / (EMDIA +EM30 + MAISDE30), 3)  AS PERCEM30,
        ROUND(CAST(MAISDE30 AS DECIMAL(6,3)) *100 / (EMDIA +EM30 + MAISDE30),3) AS PERCMAIS30
 FROM 
  (SELECT CODCLI,
          SUM(CASE WHEN CAST( (DTRECEBI- DATPRORROGA) AS INT) <=0 THEN 1 ELSE 0 END) AS EMDIA,
          SUM(CASE WHEN CAST( (DTRECEBI- DATPRORROGA) AS INT) BETWEEN 1 AND 30 THEN 1 ELSE 0 END) AS EM30,
          SUM(CASE WHEN CAST( (DTRECEBI- DATPRORROGA) AS INT) > 30 THEN 1 ELSE 0 END) AS MAISDE30,
          AVG(CAST( (DTRECEBI- DATPRORROGA) AS INT)) AS MEDIAATRASO
   FROM TBCTRC002
   WHERE DTRECEBI IS NOT NULL
   GROUP BY CODCLI           ) AS X
 ) AS W  ON W.CODCLI = T.CODCLI
WHERE T.DTRECEBI IS NULL
  AND C.CODCLI = T.CODCLI            
GROUP BY T.CODCLI,
       C.NUMCGCCPFCLI,
       C.RAZSOCCLI,
       W.PERCEMDIA,
       W.PERCEM30,
       W.PERCMAIS30
       
       
select * from TBFATU006 where RAZSOCCLI like '%salles%'       