select * from sysobjects
where name = 'TBGENE023'

SELECT CAST(X.NAME AS CHAR(40)) AS NOMECAMPO, 
       CAST(SYSTYPES.NAME AS CHAR(40)) AS TIPO, X.LENGTH AS TAMANHO 
FROM SYSCOLUMNS X, SYSTYPES
WHERE X.ID = (select ID from sysobjects
where name = 'TBGENE023'
)
AND SYSTYPES.XTYPE = X.XTYPE
ORDER BY X.COLORDER


SELECT * FROM SYSTYPES

SELECT * FROM TBCONT006