SELECT TBGENE035.CODEMP,          
       TBGENE035.QTDECARACLINITENSNFVENDAPROD, 
       TBGENE035.QTDECARACLINOBSNFVENDAPROD,   
       TBGENE035.QTDELINITENSNFVENDAPROD,      
       TBGENE035.QTDELINOBSNFVENDAPROD,        
       TBGENE035.COMPRIMENFPROD,               
       TBGENE035.NOMDOCNFPROD                 
FROM TBGENE035
WHERE TBGENE035.CODEMP = '01'
