UPDATE TBGENE060 SET NOMEPAIS = REPLACE(NOMEPAIS, 'REPUBLICA DA  ', '')
WHERE NOMEPAIS LIKE 'REPUBLICA DA  %'
go
UPDATE TBGENE060 SET NOMEPAIS = REPLACE(NOMEPAIS, 'REPUBLICA DA ', '')
WHERE NOMEPAIS LIKE 'REPUBLICA DA %'
go
UPDATE TBGENE060 SET NOMEPAIS = REPLACE(NOMEPAIS, 'REPUBLICA DO ', '')
WHERE NOMEPAIS LIKE 'REPUBLICA DO %'
go
UPDATE TBGENE060 SET NOMEPAIS = REPLACE(NOMEPAIS, 'REPUBLICA DE ', '')
WHERE NOMEPAIS LIKE 'REPUBLICA DE %'
go
UPDATE TBGENE060 SET NOMEPAIS = 'CHINA' WHERE CODPAIS = '01600'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'IRA' WHERE CODPAIS = '03727'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'SIRIA' WHERE CODPAIS = '07447'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'QUIRGUIZTAO' WHERE CODPAIS = '06254'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'COREA DO NORTE' WHERE CODPAIS = '01872'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'COREA DO SUL' WHERE CODPAIS = '01902'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'LAOS' WHERE CODPAIS = '04200'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'TANZANIA' WHERE CODPAIS = '07803'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'ESLOVAQUIA' WHERE CODPAIS = '02470'
GO
UPDATE TBGENE060 SET NOMEPAIS = 'MACEDONIA' WHERE CODPAIS = '04499'
GO