USE [BDSPARTAN]
GO

/****** Object:  StoredProcedure [dbo].[usp_Relatorio_Vendas_Anuais]    Script Date: 25/04/2019 11:47:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[usp_Relatorio_Vendas_Anuais]
                
AS
BEGIN

   DECLARE @str VARCHAR(8000)
       
   -- Vendas Anuais
   -- =============
   SELECT MONTH(TBFATU024.DATEMISSAO) AS MES,
	      YEAR(TBFATU024.DATEMISSAO) AS ANO,	      
          SUM(TBFATU025.VALTOTITEM)  AS VALOR
   INTO   #tb01Vendas
   FROM   TBFATU025, TBFATU024, TBFATU018
   WHERE  YEAR(TBFATU024.DATEMISSAO) >= YEAR(GETDATE()) - 1
     AND  TBFATU024.STANF            <> 'C'
     AND  TBFATU024.TIPOES           = 'S'
     AND  TBFATU024.TIPONF           IN ('A','V')
     AND  TBFATU024.STADEVOLUCAO     = 'N'
     AND  TBFATU025.CODEMP           = TBFATU024.CODEMP
     AND  TBFATU025.NUMNF            = TBFATU024.NUMNF
     AND  TBFATU025.SERNF            = TBFATU024.SERNF
     AND  TBFATU018.CODMOVFISC       = TBFATU025.CODMOVFISC
     AND  TBFATU018.STAVENDA         = 'S'
   GROUP BY  MONTH(TBFATU024.DATEMISSAO), YEAR(TBFATU024.DATEMISSAO)
         
   SET @str = 
   'SELECT ANO,
		   SUM(CASE WHEN MES = 1  THEN VALOR ELSE 0 END)  AS JAN,	  
           SUM(CASE WHEN MES = 2  THEN VALOR ELSE 0 END)  AS FEV,
           SUM(CASE WHEN MES = 3  THEN VALOR ELSE 0 END)  AS MAR,
           SUM(CASE WHEN MES = 4  THEN VALOR ELSE 0 END)  AS ABR,
           SUM(CASE WHEN MES = 5  THEN VALOR ELSE 0 END)  AS MAI,
           SUM(CASE WHEN MES = 6  THEN VALOR ELSE 0 END)  AS JUN,
           SUM(CASE WHEN MES = 7  THEN VALOR ELSE 0 END)  AS JUL,
           SUM(CASE WHEN MES = 8  THEN VALOR ELSE 0 END)  AS AGO,              
           SUM(CASE WHEN MES = 9  THEN VALOR ELSE 0 END)  AS SEP,
           SUM(CASE WHEN MES = 10 THEN VALOR ELSE 0 END)  AS OUT,
           SUM(CASE WHEN MES = 11 THEN VALOR ELSE 0 END)  AS NOV,
           SUM(CASE WHEN MES = 12 THEN VALOR ELSE 0 END)  AS DEZ
   FROM #tb01Vendas
   GROUP BY ANO
   ORDER BY ANO'
                              
   EXEC(@str)
   DROP TABLE #tb01Vendas

END 
GO

