CREATE TABLE TESTE (CODIGO CHAR(2),
                    DESMAT1 CHAR(20),
                    DESMAT2 CHAR(20),
                    DESMAT AS CASE WHEN DESMAT2 IS NULL THEN DESMAT1 ELSE DESMAT2 END )

SELECT * FROM TESTE

INSERT INTO TESTE VALUES ('01', 'DESMAT1', NULL)
INSERT INTO TESTE VALUES ('04', NULL, '2DESMAT2')
INSERT INTO TESTE VALUES ('01', NULL, 'DESMAT3', 'DESMAT3')


CREATE VIEW  VWTESTE
AS 
SELECT CODIGO, DESMAT FROM TESTE

CREATE TRIGGER INSTTESTE ON VWTESTE
INSTEAD OF INSERT
AS 
BEGIN
   INSERT INTO TESTE (CODIGO, DESMAT1, DESMAT2)
   SELECT I.CODIGO,
          CASE SUBSTRING(I.DESMAT, 1, 1)
            WHEN '1' THEN I.DESMAT ELSE NULL END,
          CASE SUBSTRING(I.DESMAT, 1, 1)
            WHEN '2' THEN I.DESMAT ELSE NULL END
   FROM inserted I

END

insert into vwteste values ('02', '1teste')
insert into vwteste values ('03', '2teste')
insert into vwteste values ('05', '1teste')

SELECT * FROM VWTESTE
SELECT * FROM TESTE