DECLARE @datIni DATETIME,
        @datFim DATETIME,
        @codBanco  char(15),
        @codAgencia char(15) 

SET @datIni = '2012-09-01'
SET @datfIM = '2012-09-30'

set @codBanco  = '001'
set @codAgencia = '3360-X'

SELECT *, INICIAL + ENTRADA + SAIDA AS SALDO FROM 
(
SELECT CODEMP, CODBANCO,  CODAGENCIA,
       '1_CONTABIL' AS TIPO, 
       SUM( CASE WHEN DATMOVTO < @datIni THEN (VALMOVTO * SINAL) ELSE 0 END ) AS INICIAL,
       SUM( CASE WHEN (DATMOVTO BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'E' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS ENTRADA,
       SUM( CASE WHEN (DATMOVTO BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'S' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS SAIDA

 FROM TBCONB001
 WHERE (DATMOVTO  <= @datFim)
 GROUP BY CODEMP, CODBANCO,  CODAGENCIA
 UNION
SELECT CODEMP, CODBANCO,  CODAGENCIA,
       '2_BANCARIO', 
       SUM( CASE WHEN DATBAIXA < @datIni THEN (VALMOVTO * SINAL) ELSE 0 END ) AS INICIAL,
       SUM( CASE WHEN (DATBAIXA BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'E' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS ENTRADA,
       SUM( CASE WHEN (DATBAIXA BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'S' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS SAIDA

 FROM TBCONB001
 WHERE (DATBAIXA  <= @datFim)
 GROUP BY CODEMP, CODBANCO,  CODAGENCIA
 UNION
SELECT CODEMP, CODBANCO,  CODAGENCIA,
       '3_A COMPENSAR', 
       SUM( CASE WHEN DATMOVTO < @datIni THEN (VALMOVTO * SINAL) ELSE 0 END ) AS INICIAL,
       SUM( CASE WHEN (DATMOVTO BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'E' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS ENTRADA,
       SUM( CASE WHEN (DATMOVTO BETWEEN @datIni AND @datFim) AND TIPOMOVTO = 'S' THEN (VALMOVTO * SINAL) ELSE 0 END ) AS SAIDA

 FROM TBCONB001
 WHERE (DATMOVTO  <= @datFim)
   AND DATBAIXA IS NULL
 GROUP BY CODEMP, CODBANCO,  CODAGENCIA
 ) AS X
 WHERE CODEMP   = '01'
   AND CODBANCO = @codBanco
   AND CODAGENCIA = @codAgencia
 ORDER BY 1,2,3


CREATE INDEX INDTBCONB001_BANCO_DATBAIXA ON TBCONB001
(CODEMP, CODBANCO, CODAGENCIA, DATBAIXA)
INCLUDE (TIPOMOVTO, VALMOVTO) 

CREATE INDEX INDTBCONB001_BANCO_DATMOVTO ON TBCONB001
(CODEMP, CODBANCO, CODAGENCIA, DATMOVTO)
INCLUDE (TIPOMOVTO, VALMOVTO) 


ALTER TABLE TBCONB001 ADD SINAL AS (CASE TIPOMOVTO WHEN 'S' THEN -1 ELSE 1 END)