  RESTORE DATABASE [BDPROCESSUS] 
  FROM  DISK = 'D:\BD\2008R2\PROCESSUS\BDNOTA.BAK' WITH  FILE = 1,  
  MOVE 'BDINTEG_Data' TO 'd:\BD\2008R2\PROCESSUS\BDPROCESSUS.MDF',  
  MOVE 'BDINTEG_Log'  TO 'd:\BD\2008R2\PROCESSUS\BDPROCESSUS.LDF',  
  NOUNLOAD,  REPLACE,  STATS = 5