SELECT ANOLOTE,
       MESLOTE,
       NUMLOTE,
       NUMLANC,
       ROUND( SUM ( CASE TIPMOVTO WHEN 'D' THEN VALMOVTO ELSE 0 END ), 2 ) AS DEBITO,
       ROUND( SUM ( CASE TIPMOVTO WHEN 'C' THEN VALMOVTO ELSE 0 END ), 2 ) AS CREDITO
FROM TBCONT013
WHERE ANOLOTE = '2010'
GROUP BY ANOLOTE,
         MESLOTE,
         NUMLOTE,
         NUMLANC        
HAVING ROUND( SUM ( CASE TIPMOVTO WHEN 'D' THEN VALMOVTO ELSE 0 END ), 2 ) <>
       ROUND( SUM ( CASE TIPMOVTO WHEN 'C' THEN VALMOVTO ELSE 0 END ), 2 ) 
       
       
       
       
SELECT CODENTRESREF FROM TBGENE035       

SELECT * FROM TBFATU006


SELECT C.CODCLI,RAZSOCCLI,NOMFANTASCLI,CODVEND,ENDCLI,NUMENDCLI,COMPLENDCLI,BAIRROCLI,CIDADECLI,CODUF,CEPCLI,TELCLI,CONTATOCLI,FAXCLI,NUMCGCCPFCLI,INSCRESTA,INSCRMUNIC,EMAIL2,DATCADAST,X.OBSCLI
FROM TBFATU006 C, TBFATU007 X
WHERE 0=1
